#!/usr/bin/env python3

import readline  # noqa: F401

from apps.base.config_update import check_update
from apps.utility.colors import *
from lib.smf.core.booting.boot import *
from lib.ui.banner import *
from lib.smf.core.console.engine import Context 

def main():
    boot()
    banner()
    check_update()
    core = Context()

    while not core.exit:
        p_mod = core.current_module_name if core.current_module else "~"
        
        try:
            print(f"{CC.CYAN}┌─({CC.BLUE}storm{CC.YELLOW}<⚡>{CC.BLUE}framework{CC.CYAN}){CC.RESET}-{CC.RED}[{p_mod}]{CC.RESET}")
            promp = f"{CC.CYAN}└─{CC.BLUE}➤ {CC.RESET}"
            user_input = input(promp).strip().split()
        except KeyboardInterrupt: return
        except EOFError: break

        if not user_input: 
            continue

        # parsing input
        cmd = user_input[0].lower()
        args = user_input[1:]

        # Send input data to the console
        core.dispatch(cmd, args)

if __name__ == "__main__":
    main()
