#!/usr/bin/env python3

# -- https://github.com/StormWorld0/storm-framework
# -- SMF License
import smf
import sys

def main():

    try:
        from apps.utility.update import run_update as update

        update()
    except ImportError as d:
        smf.printf(f"ERROR IMPORT UPDATE =>", d, file=sys.stderr, flush=True)
    except Exception as e:
        smf.printf(f"ERROR UPDATE =>", e, file=sys.stderr, flush=True)

if __name__ == "__main__":
    main()
