#!/usr/bin/env python3

import os
import readline  # noqa: F401
import lib.smf.core.sf.ldch as ldch

from apps.utility.colors import C
from lib.smf.core.booting.boot import *
from lib.core import handler as ex

def main():
    boot()
    banner()

    current_module = None
    current_module_name = ""

    # Global options
    options = {
        "IP": "",
        "PORT": "",
        "PASS": "",
        "URL": "",
        "EMAIL": "",
        "HASH": "",
        "MESSAGE": "",
        "USER": "",
        "ID": "",
        "COUNT": "",
        "PATH": "",
        "INTERFACE": "",
        "THREAD": "",
        "DOMAIN": "",
        "HOSTNAME": "",
        "MODULE": ""
    }
    options = ldch.session(options)

    while True:
        START = "\001"
        END = "\002"

        BLUE = f"{START}{C.BLUE}{END}"
        CYAN = f"{START}{C.MENU}{END}"
        YELLOW = f"{START}{C.INPUT}{END}"
        RED = f"{START}{C.ERROR}{END}"
        RESET = f"{START}{C.RESET}{END}"

        p_mod = current_module_name if current_module else "~"
        try:
            print(f"{CYAN}┌─({BLUE}storm{YELLOW}<⚡>{BLUE}framework{CYAN}){RESET}-{RED}[{p_mod}]{RESET}")
            promp = f"{CYAN}└─{BLUE}➤ {RESET}"
            user_input = input(promp).strip().split()
        except KeyboardInterrupt: return
        except EOFError: break

        if not user_input: continue

        cmd = user_input[0].lower()
        args = user_input[1:]

        # Wrap all data into Context
        context = {
            "current_module": current_module,
            "current_module_name": current_module_name,
            "options": options,
            "exit": False
        }

        # HAND IT OVER TO THE FOREMAN (HANDLER)
        new_context = ex.execute(cmd, args, context)

        if new_context:
            current_module = new_context["current_module"]
            current_module_name = new_context["current_module_name"]
            options = new_context["options"]

            if new_context.get("exit"): break
        else:
            print(f"[-] Unknown Command: {cmd} => Run the {C.SUCCESS}help{C.RESET} command for more details.")

if __name__ == "__main__":
    main()
